# Generated by Django 2.1.5 on 2023-05-27 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0007_boss'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='城市')),
                ('count', models.IntegerField(verbose_name='人口')),
                ('img', models.FileField(max_length=320, upload_to='city/', verbose_name='Logo')),
            ],
        ),
    ]
